modLoader="javafml"
loaderVersion="[52,)"
license="MIT"
[[mods]]
modId="sysshop"
version="0.0.1"
displayName="sysshop"
authors="CircleKey"
description='''玩家提交物品换取系统无限供货的奖励，并可使用游戏内管理员界面配置交易。'''
[[dependencies.sysshop]]
modId="forge"
mandatory=true
versionRange="[52,)"
ordering="NONE"
side="BOTH"
[[dependencies.sysshop]]
modId="minecraft"
mandatory=true
versionRange="[1.21.1,1.22)"
ordering="NONE"
side="BOTH"
