org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
forge_version=52.1.16
forge_version_range=[52,)
loader_version_range=[52,)
mapping_channel=official
mapping_version=1.21.1
mod_id=sysshop
mod_name=sysshop
mod_license=MIT
mod_version=0.0.1
mod_group_id=com.sysshop
mod_authors=CircleKey
mod_description=Player-owned barter shops with 54-slot stock, plus an unlimited system shop in multiplayer.